baseURL = "https://resume-8jofa.ondigitalocean.app/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Mason CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
